// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoveEnergia.Billing.Data.Context;

#nullable disable

namespace MoveEnergia.Billing.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251011022807_AddDealsAddressFields2")]
    partial class AddDealsAddressFields2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MoveEnergia.Billing.Core.Entity.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Bairro");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CEP");

                    b.Property<int>("CityId")
                        .HasColumnType("int")
                        .HasColumnName("CityId");

                    b.Property<string>("Complemento")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Complemento");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("CustomerId");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Logradouro");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Numero");

                    b.HasKey("Id")
                        .HasName("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Addresses", "dbo");
                });

            modelBuilder.Entity("MoveEnergia.Billing.Core.Entity.City", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Nome");

                    b.Property<int>("UFId")
                        .HasColumnType("int")
                        .HasColumnName("UFId");

                    b.HasKey("Id")
                        .HasName("Id");

                    b.ToTable("Cities", "dbo");
                });

            modelBuilder.Entity("MoveEnergia.Billing.Core.Entity.ConsumerTipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("CustomerId");

                    b.HasKey("Id")
                        .HasName("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("ConsumerTipos", "dbo");
                });

            modelBuilder.Entity("MoveEnergia.Billing.Core.Entity.ConsumerUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apelido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cnpj")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Cnpj");

                    b.Property<byte?>("ConnectionId")
                        .HasColumnType("tinyint")
                        .HasColumnName("ConnectionId");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreationTime");

                    b.Property<long?>("CreatorUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("CreatorUserId");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("CustomerId");

                    b.Property<DateTime?>("DataAssinatura")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataAssinatura");

                    b.Property<DateTime?>("DataMigracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataMigracao");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("DeleterUserId");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletionTime");

                    b.Property<decimal?>("DemandaContradada")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("DemandaContradada");

                    b.Property<decimal?>("DemandaContradadaForaPonta")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("DemandaContradadaForaPonta");

                    b.Property<decimal?>("DemandaContradadaPonta")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("DemandaContradadaPonta");

                    b.Property<int>("DistributorId")
                        .HasColumnType("int")
                        .HasColumnName("DistributorId");

                    b.Property<string>("Enquadramento")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Enquadramento");

                    b.Property<DateTime?>("ExpectativaOperacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("ExpectativaOperacao");

                    b.Property<decimal?>("FatorCapacidade")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("FatorCapacidade");

                    b.Property<string>("Fonte")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Fonte");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastModificationTime");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("LastModifierUserId");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Nome");

                    b.Property<string>("NomeUsina")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NomeUsina");

                    b.Property<decimal?>("PotenciakWCA")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PotenciakWCA");

                    b.Property<string>("SenhaDist")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SenhaDist");

                    b.Property<byte>("StateId")
                        .HasColumnType("tinyint")
                        .HasColumnName("StateId");

                    b.Property<byte>("SubgroupId")
                        .HasColumnType("tinyint")
                        .HasColumnName("SubgroupId");

                    b.Property<byte>("TariffModalityId")
                        .HasColumnType("tinyint")
                        .HasColumnName("Tariff_ModalityId");

                    b.Property<int>("TenantId")
                        .HasColumnType("int")
                        .HasColumnName("TenantId");

                    b.Property<byte>("Tipo")
                        .HasColumnType("tinyint");

                    b.Property<string>("UC")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UC");

                    b.Property<byte>("UnidadeStatusId")
                        .HasColumnType("tinyint")
                        .HasColumnName("UnidadeStatusId");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("UserId");

                    b.Property<decimal?>("ValorGestao")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ValorGestao");

                    b.HasKey("Id")
                        .HasName("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DistributorId");

                    b.HasIndex("StateId");

                    b.HasIndex("SubgroupId");

                    b.HasIndex("TariffModalityId");

                    b.HasIndex("UserId");

                    b.ToTable("ConsumerUnit", "dbo");
                });

            modelBuilder.Entity("MoveEnergia.Billing.Core.Entity.ConsumerUnitCustumer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreateDate");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("CustomerId");

                    b.Property<string>("UC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UC");

                    b.HasKey("Id")
                        .HasName("Id");

                    b.ToTable("ConsumerUnitCustumer", "dbo");
                });

            modelBuilder.Entity("MoveEnergia.Billing.Core.Entity.ConsumerUnitMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConsumerUnitId")
                        .HasColumnType("int")
                        .HasColumnName("ConsumerUnitId");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreationTime");

                    b.Property<long?>("CreatorUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("CreatorUserId");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("Date");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("DeleterUserId");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletionTime");

                    b.Property<decimal?>("ForaPonta")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ForaPonta");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastModificationTime");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("LastModifierUserId");

                    b.Property<decimal?>("Ponta")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Ponta");

                    b.Property<decimal?>("Value")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Value");

                    b.HasKey("Id")
                        .HasName("Id");

                    b.HasIndex("ConsumerUnitId");

                    b.ToTable("ConsumerUnitMeasurements", "dbo");
                });

            modelBuilder.Entity("MoveEnergia.Billing.Core.Entity.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("CustomerId");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Nome");

                    b.Property<int>("PositionId")
                        .HasColumnType("int")
                        .HasColumnName("PositionId");

                    b.Property<int>("TenantId")
                        .HasColumnType("int")
                        .HasColumnName("TenantId");

                    b.HasKey("Id")
                        .HasName("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PositionId")
                        .IsUnique();

                    b.ToTable("Contacts", "dbo");
                });

            modelBuilder.Entity("MoveEnergia.Billing.Core.Entity.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Nome");

                    b.HasKey("Id")
                        .HasName("Id");

                    b.ToTable("Country", "dbo");
                });

            modelBuilder.Entity("MoveEnergia.Billing.Core.Entity.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Code");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreationTime");

                    b.Property<long?>("CreatorUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("CreatorUserId");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("DeleterUserId");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletionTime");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastModificationTime");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("LastModifierUserId");

                    b.Property<byte>("Mercado")
                        .HasColumnType("tinyint")
                        .HasColumnName("Mercado");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<Guid?>("PathKey")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PathKey");

                    b.Property<string>("RazoSocial")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RazoSocial");

                    b.Property<int>("TenantId")
                        .HasColumnType("int")
                        .HasColumnName("TenantId");

                    b.Property<byte>("TipoCustomer")
                        .HasColumnType("tinyint")
                        .HasColumnName("TipoCustomer");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("UserId");

                    b.HasKey("Id")
                        .HasName("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Customers", "dbo");
                });

            modelBuilder.Entity("MoveEnergia.Billing.Core.Entity.Deals", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("CEP")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Deal_custom_field_CEP");

                    b.Property<string>("CNPJCPF")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Deal_custom_field_CNPJ_CPF");

                    b.Property<string>("CoopConsumoMedioKWh")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Deal_custom_field_ConsumidorCoopConsumoMedioKWh");

                    b.Property<string>("CoopModalidadeDesconto")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Deal_custom_field_CoopModalidadeDesconto");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreationTime");

                    b.Property<int?>("CreatorUserID")
                        .HasColumnType("int")
                        .HasColumnName("CreatorUserID");

                    b.Property<string>("CsAutoConsumo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Deal_custom_field_CS_Autoconsumo");

                    b.Property<string>("DealId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DealId");

                    b.Property<string>("DealsWin")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Deals_Win");

                    b.Property<int?>("DeleterUserId")
                        .HasColumnType("int")
                        .HasColumnName("DeleterUserId");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletionTime");

                    b.Property<string>("DescAdicionalPercent")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Deal_custom_field_DescAdicionalPercent");

                    b.Property<string>("DescAmarela")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Deal_custom_field_DescAmarela");

                    b.Property<string>("DescVerde")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Deal_custom_field_DescVerde");

                    b.Property<string>("DescVermelha1")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Deal_custom_field_DescVermelha1");

                    b.Property<string>("DescVermelha2")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Deal_custom_field_DescVermelha2");

                    b.Property<string>("Distribuidora")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Deal_custom_field_Distribuidora");

                    b.Property<string>("EndBairro")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Deal_custom_field_EndBairro");

                    b.Property<string>("EndCidade")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Deal_custom_field_EndCidade");

                    b.Property<string>("EndComplemento")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Deal_custom_field_EndComplemento");

                    b.Property<string>("EndNumero")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Deal_custom_field_EndNumero");

                    b.Property<string>("EndRua")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Deal_custom_field_EndRua");

                    b.Property<string>("EndUF")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Deal_custom_field_EndUF");

                    b.Property<string>("FechadoEm")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FechadoEm");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastModificationTime");

                    b.Property<int?>("LastModifierUserID")
                        .HasColumnType("int")
                        .HasColumnName("LastModifierUserId");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<string>("Pipeline")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Deal_pipeline_name");

                    b.Property<string>("Stage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Deal_stage_name");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Status");

                    b.Property<string>("SubOrigem")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Deal_custom_field_Suborigem");

                    b.Property<string>("Titularidade")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Deal_custom_field_Titularidade");

                    b.Property<string>("UC")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Deal_custom_field_UC");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Value");

                    b.HasKey("Id")
                        .HasName("Id");

                    b.ToTable("Deals", "dbo");
                });

            modelBuilder.Entity("MoveEnergia.Billing.Core.Entity.DetalhesFaturaCache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnotacaoFatura")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AnotacaoFatura");

                    b.Property<DateTime?>("Atualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("Atualizacao");

                    b.Property<DateTime>("Criacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("Criacao");

                    b.Property<DateTime?>("DataEmissao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataEmissao");

                    b.Property<DateTime?>("DataVencimento")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataVencimento");

                    b.Property<string>("Distribuidora")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Distribuidora");

                    b.Property<string>("DistribuidoraRD")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DistribuidoraRD");

                    b.Property<string>("DocumentoProprietario")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DocumentoProprietario");

                    b.Property<string>("EmailProprietario")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EmailProprietario");

                    b.Property<bool>("Emitida")
                        .HasColumnType("bit")
                        .HasColumnName("Emitida");

                    b.Property<bool>("Excluida")
                        .HasColumnType("bit")
                        .HasColumnName("Excluida");

                    b.Property<bool>("FaturaFraca")
                        .HasColumnType("bit")
                        .HasColumnName("FaturaFraca");

                    b.Property<int>("FaturaId")
                        .HasColumnType("int")
                        .HasColumnName("FaturaId");

                    b.Property<bool>("FaturaInterna")
                        .HasColumnType("bit")
                        .HasColumnName("FaturaInterna");

                    b.Property<string>("Hash")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Hash");

                    b.Property<int>("IdConta")
                        .HasColumnType("int")
                        .HasColumnName("IdConta");

                    b.Property<int>("MesReferencia")
                        .HasColumnType("int")
                        .HasColumnName("MesReferencia");

                    b.Property<bool>("NecessitaRecalculo")
                        .HasColumnType("bit")
                        .HasColumnName("NecessitaRecalculo");

                    b.Property<string>("NomeConta")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NomeConta");

                    b.Property<string>("QtEnergiaCompensadaHfp")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("QT_ENERGIA_COMPENSADA_HFP");

                    b.Property<int>("QuantidadeFaturas")
                        .HasColumnType("int")
                        .HasColumnName("QuantidadeFaturas");

                    b.Property<decimal?>("Rateio")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Rateio");

                    b.Property<bool>("SemUCNoRD")
                        .HasColumnType("bit")
                        .HasColumnName("SemUCNoRD");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Status");

                    b.Property<string>("SubOrigem")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SubOrigem");

                    b.Property<bool>("TemAnotacaoFatura")
                        .HasColumnType("bit")
                        .HasColumnName("TemAnotacaoFatura");

                    b.Property<bool>("TemAnotacaoGerente")
                        .HasColumnType("bit")
                        .HasColumnName("TemAnotacaoGerente");

                    b.Property<bool>("TemAumento")
                        .HasColumnType("bit")
                        .HasColumnName("TemAumento");

                    b.Property<bool>("TemDesconto")
                        .HasColumnType("bit")
                        .HasColumnName("TemDesconto");

                    b.Property<bool>("TemEscritorioPagamentoAtivo")
                        .HasColumnType("bit")
                        .HasColumnName("TemEscritorioPagamentoAtivo");

                    b.Property<bool>("TemInjecaoEnergiaPropria")
                        .HasColumnType("bit")
                        .HasColumnName("TemInjecaoEnergiaPropria");

                    b.Property<decimal?>("Total")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Total");

                    b.Property<string>("Uc")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Uc");

                    b.Property<string>("UrlArquivo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UrlArquivo");

                    b.Property<string>("VlEconomia")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("VL_ECONOMIA");

                    b.Property<string>("VlItemRegra")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("VL_ITEM_REGRA");

                    b.Property<string>("VlSemConsorcio")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("VL_SEM_CONSORCIO");

                    b.Property<string>("VlTarEnergiaInjetadaHfp")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("VL_TAR_ENERGIA_INJETADA_HFP");

                    b.Property<string>("VlTarEnergiainjetadaHfpDescontoAplicado")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("VL_TAR_ENERGIA_INJETADA_HFP_DESCONTO_APLICADO");

                    b.HasKey("Id")
                        .HasName("Id");

                    b.ToTable("DetalhesFaturaCache", "dbo");
                });

            modelBuilder.Entity("MoveEnergia.Billing.Core.Entity.Distributor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("COFINSComum")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("COFINSComum");

                    b.Property<decimal>("COFINSInjetada")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("COFINSInjetada");

                    b.Property<string>("Cnpj")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Cnpj");

                    b.Property<DateTime>("DataReajustePrevisto")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataReajustePrevisto");

                    b.Property<DateTime>("DataReajusteRealizado")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ICMSComum")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ICMSComum");

                    b.Property<decimal>("ICMSInjetada")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ICMSInjetada");

                    b.Property<decimal>("ICMSTE")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ICMSTE");

                    b.Property<decimal>("ICMSTUSDc")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ICMSTUSDc");

                    b.Property<int?>("IdCooperativa")
                        .HasColumnType("int")
                        .HasColumnName("ID_COOPERATIVA");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Nome");

                    b.Property<string>("NomeDeApresentacao")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NomeDeApresentacao");

                    b.Property<decimal>("PISComum")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PISComum");

                    b.Property<decimal>("PISInjetada")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PISInjetada");

                    b.Property<string>("Sigla")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Sigla");

                    b.Property<string>("UF")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UF");

                    b.HasKey("Id")
                        .HasName("Id");

                    b.ToTable("Distributor", "dbo");
                });

            modelBuilder.Entity("MoveEnergia.Billing.Core.Entity.Email", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Address");

                    b.Property<int>("ContactId")
                        .HasColumnType("int")
                        .HasColumnName("ContactId");

                    b.HasKey("Id")
                        .HasName("Id");

                    b.HasIndex("ContactId");

                    b.ToTable("Emails", "dbo");
                });

            modelBuilder.Entity("MoveEnergia.Billing.Core.Entity.FaturaCache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataEnviadoWhatsapp")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataEnviadoWhatsapp");

                    b.Property<bool>("EnviadoWhatsapp")
                        .HasColumnType("bit")
                        .HasColumnName("EnviadoWhatsapp");

                    b.Property<int>("FaturaId")
                        .HasColumnType("int")
                        .HasColumnName("FaturaId");

                    b.Property<string>("Hash")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Hash");

                    b.Property<int>("MesReferencia")
                        .HasColumnType("int")
                        .HasColumnName("MesReferencia");

                    b.Property<string>("NumeroEnviado")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NumeroEnviado");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Status");

                    b.Property<string>("StatusEnviado")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("StatusEnviado");

                    b.Property<string>("SubOrigem")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SubOrigem");

                    b.Property<int>("Tentativa")
                        .HasColumnType("int")
                        .HasColumnName("Tentativa");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Token");

                    b.Property<string>("UrlBoleto")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UrlBoleto");

                    b.HasKey("Id")
                        .HasName("Id");

                    b.ToTable("FaturaCache", "dbo");
                });

            modelBuilder.Entity("MoveEnergia.Billing.Core.Entity.FederativeUnit", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<int>("CountryId")
                        .HasColumnType("int")
                        .HasColumnName("CountryId");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Nome");

                    b.Property<string>("Sigla")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Sigla");

                    b.HasKey("Id")
                        .HasName("Id");

                    b.ToTable("FederativeUnits", "dbo");
                });

            modelBuilder.Entity("MoveEnergia.Billing.Core.Entity.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("Id")
                        .HasName("Id");

                    b.ToTable("Positions", "dbo");
                });

            modelBuilder.Entity("MoveEnergia.Billing.Core.Entity.RdFieldsIntegration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Callback")
                        .HasColumnType("bit")
                        .HasColumnName("Callback");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DataType");

                    b.Property<string>("IdRd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("IdRd");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Label");

                    b.Property<bool>("OrigemRD")
                        .HasColumnType("bit")
                        .HasColumnName("OrigemRD");

                    b.Property<bool>("Required")
                        .HasColumnType("bit")
                        .HasColumnName("Required");

                    b.HasKey("Id")
                        .HasName("Id");

                    b.ToTable("RdFieldsIntegration", "dbo");
                });

            modelBuilder.Entity("MoveEnergia.Billing.Core.Entity.State", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint")
                        .HasColumnName("Id");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.HasKey("Id")
                        .HasName("Id");

                    b.ToTable("States", "dbo");
                });

            modelBuilder.Entity("MoveEnergia.Billing.Core.Entity.Subgroup", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint")
                        .HasColumnName("Id");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.HasKey("Id")
                        .HasName("Id");

                    b.ToTable("Subgroup", "dbo");
                });

            modelBuilder.Entity("MoveEnergia.Billing.Core.Entity.TariffModality", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint")
                        .HasColumnName("Id");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.HasKey("Id")
                        .HasName("Id");

                    b.ToTable("Tariff_Modality", "dbo");
                });

            modelBuilder.Entity("MoveEnergia.Billing.Core.Entity.Telephone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContactId")
                        .HasColumnType("int")
                        .HasColumnName("ContactId");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("Id");

                    b.HasIndex("ContactId");

                    b.ToTable("Telephones", "dbo");
                });

            modelBuilder.Entity("MoveEnergia.Billing.Core.Entity.Tenants", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConnectionString")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ConnectionString");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreationTime");

                    b.Property<long?>("CreatorUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("CreatorUserId");

                    b.Property<long?>("DeleterUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("DeleterUserId");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletionTime");

                    b.Property<int?>("EditionId")
                        .HasColumnType("int")
                        .HasColumnName("EditionId");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastModificationTime");

                    b.Property<long?>("LastModifierUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("LastModifierUserId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<string>("RdStationSubOrigem")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RdStationSubOrigem");

                    b.Property<string>("RdStationToken")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RdStationToken");

                    b.Property<string>("TenancyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenancyName");

                    b.HasKey("Id")
                        .HasName("Id");

                    b.ToTable("AbpTenants", "dbo");
                });

            modelBuilder.Entity("MoveEnergia.Billing.Core.Entity.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int")
                        .HasColumnName("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreationTime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EmailAddress");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("IsEmailConfirmed");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("IsLockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("LockoutEndDateUtc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NormalizedEmailAddress");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NormalizedUserName");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Password");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("IsPhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SecurityStamp");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Surname");

                    b.Property<int?>("TenantId")
                        .HasColumnType("int")
                        .HasColumnName("TenantId");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("IsTwoFactorEnabled");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UserName");

                    b.HasKey("Id")
                        .HasName("Id");

                    b.ToTable("AbpUsers", "dbo");
                });

            modelBuilder.Entity("MoveEnergia.Billing.Core.Entity.Address", b =>
                {
                    b.HasOne("MoveEnergia.Billing.Core.Entity.City", "City")
                        .WithMany("Address")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoveEnergia.Billing.Core.Entity.Customer", "Customer")
                        .WithMany("Addresses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("MoveEnergia.Billing.Core.Entity.City", b =>
                {
                    b.HasOne("MoveEnergia.Billing.Core.Entity.FederativeUnit", "UF")
                        .WithOne("City")
                        .HasForeignKey("MoveEnergia.Billing.Core.Entity.City", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UF");
                });

            modelBuilder.Entity("MoveEnergia.Billing.Core.Entity.ConsumerTipo", b =>
                {
                    b.HasOne("MoveEnergia.Billing.Core.Entity.Customer", "Customer")
                        .WithMany("ConsumerTipos")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("MoveEnergia.Billing.Core.Entity.ConsumerUnit", b =>
                {
                    b.HasOne("MoveEnergia.Billing.Core.Entity.Customer", "Customer")
                        .WithMany("ConsumerUnit")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoveEnergia.Billing.Core.Entity.Distributor", "Distributor")
                        .WithMany()
                        .HasForeignKey("DistributorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoveEnergia.Billing.Core.Entity.State", "State")
                        .WithMany("ConsumerUnit")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoveEnergia.Billing.Core.Entity.Subgroup", "Subgroup")
                        .WithMany("ConsumerUnit")
                        .HasForeignKey("SubgroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoveEnergia.Billing.Core.Entity.TariffModality", "TariffModality")
                        .WithMany()
                        .HasForeignKey("TariffModalityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoveEnergia.Billing.Core.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Distributor");

                    b.Navigation("State");

                    b.Navigation("Subgroup");

                    b.Navigation("TariffModality");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MoveEnergia.Billing.Core.Entity.ConsumerUnitMeasurement", b =>
                {
                    b.HasOne("MoveEnergia.Billing.Core.Entity.ConsumerUnit", "ConsumerUnit")
                        .WithMany("ConsumerUnitMeasurements")
                        .HasForeignKey("ConsumerUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConsumerUnit");
                });

            modelBuilder.Entity("MoveEnergia.Billing.Core.Entity.Contact", b =>
                {
                    b.HasOne("MoveEnergia.Billing.Core.Entity.Customer", null)
                        .WithMany("Contacts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoveEnergia.Billing.Core.Entity.Position", "Position")
                        .WithOne("Contact")
                        .HasForeignKey("MoveEnergia.Billing.Core.Entity.Contact", "PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Position");
                });

            modelBuilder.Entity("MoveEnergia.Billing.Core.Entity.Customer", b =>
                {
                    b.HasOne("MoveEnergia.Billing.Core.Entity.User", "User")
                        .WithOne("Customer")
                        .HasForeignKey("MoveEnergia.Billing.Core.Entity.Customer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MoveEnergia.Billing.Core.Entity.Email", b =>
                {
                    b.HasOne("MoveEnergia.Billing.Core.Entity.Contact", "Contact")
                        .WithMany("Emails")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("MoveEnergia.Billing.Core.Entity.FederativeUnit", b =>
                {
                    b.HasOne("MoveEnergia.Billing.Core.Entity.Country", "Country")
                        .WithOne("FederativeUnit")
                        .HasForeignKey("MoveEnergia.Billing.Core.Entity.FederativeUnit", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("MoveEnergia.Billing.Core.Entity.Telephone", b =>
                {
                    b.HasOne("MoveEnergia.Billing.Core.Entity.Contact", "Contact")
                        .WithMany("Telephones")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("MoveEnergia.Billing.Core.Entity.City", b =>
                {
                    b.Navigation("Address");
                });

            modelBuilder.Entity("MoveEnergia.Billing.Core.Entity.ConsumerUnit", b =>
                {
                    b.Navigation("ConsumerUnitMeasurements");
                });

            modelBuilder.Entity("MoveEnergia.Billing.Core.Entity.Contact", b =>
                {
                    b.Navigation("Emails");

                    b.Navigation("Telephones");
                });

            modelBuilder.Entity("MoveEnergia.Billing.Core.Entity.Country", b =>
                {
                    b.Navigation("FederativeUnit");
                });

            modelBuilder.Entity("MoveEnergia.Billing.Core.Entity.Customer", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("ConsumerTipos");

                    b.Navigation("ConsumerUnit");

                    b.Navigation("Contacts");
                });

            modelBuilder.Entity("MoveEnergia.Billing.Core.Entity.FederativeUnit", b =>
                {
                    b.Navigation("City");
                });

            modelBuilder.Entity("MoveEnergia.Billing.Core.Entity.Position", b =>
                {
                    b.Navigation("Contact")
                        .IsRequired();
                });

            modelBuilder.Entity("MoveEnergia.Billing.Core.Entity.State", b =>
                {
                    b.Navigation("ConsumerUnit");
                });

            modelBuilder.Entity("MoveEnergia.Billing.Core.Entity.Subgroup", b =>
                {
                    b.Navigation("ConsumerUnit");
                });

            modelBuilder.Entity("MoveEnergia.Billing.Core.Entity.User", b =>
                {
                    b.Navigation("Customer")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
