@MoveEnergia.Billing.Api_HostAddress = http://localhost:5026

GET {{MoveEnergia.Billing.Api_HostAddress}}/v1/weatherforecast/
Accept: application/json

### Buscar todos os tenants
GET {{MoveEnergia.Billing.Api_HostAddress}}/v1/tenants/
Accept: application/json

### Buscar todos os tenants
GET {{MoveEnergia.Billing.Api_HostAddress}}/v1/ConsumerUnit/
Accept: application/json

###
